#!/usr/bin/env python3
"""
formlabs.py — Formlabs butterfly logo spinning in center, orange twinkling stars background.
"""
import math
import time
import random
from PIL import Image, ImageDraw

try:
    from rgbmatrix import RGBMatrix, RGBMatrixOptions
    from notify import check_and_show_notification
except ImportError:
    from RGBMatrixEmulator import RGBMatrix, RGBMatrixOptions
    def check_and_show_notification(m, c): pass

SPIN_SPEED = 80  # degrees per second

# 3x5 pixel font — each entry is 5 rows, 3 bits wide (MSB = left)
_GLYPHS = {
    '0': [0b111,0b101,0b101,0b101,0b111],
    '1': [0b010,0b110,0b010,0b010,0b111],
    '2': [0b111,0b001,0b111,0b100,0b111],
    '3': [0b111,0b001,0b111,0b001,0b111],
    '4': [0b101,0b101,0b111,0b001,0b001],
    '5': [0b111,0b100,0b111,0b001,0b111],
    '6': [0b111,0b100,0b111,0b101,0b111],
    '7': [0b111,0b001,0b001,0b001,0b001],
    '8': [0b111,0b101,0b111,0b101,0b111],
    '9': [0b111,0b101,0b111,0b001,0b111],
    ':': [0b000,0b010,0b000,0b010,0b000],
}

def _draw_text(img, x, y, text, color):
    for ch in text:
        for row, bits in enumerate(_GLYPHS.get(ch, [])):
            for col in range(3):
                if bits & (1 << (2 - col)):
                    img.putpixel((x + col, y + row), color)
        x += 4  # 3px glyph + 1px gap
SPRITE_PATH = "/home/tidabit1977/butterfly_sprite.png"


def _load_butterfly():
    """Load the SVG-derived sprite generated by gen_butterfly.py."""
    return Image.open(SPRITE_PATH).convert("RGBA")


def _make_stars(n=20, seed=7):
    """Fixed star positions with random phase/speed, avoiding the center."""
    rng = random.Random(seed)
    stars = []
    while len(stars) < n:
        x = rng.randint(0, 63)
        y = rng.randint(0, 31)
        if abs(x - 32) < 17 and abs(y - 16) < 13:
            continue
        color = 'blue' if rng.random() < 0.5 else 'orange'
        stars.append((x, y, rng.uniform(0, math.pi * 2), rng.uniform(1.5, 4.0), color))
    return stars


_BUTTERFLY = _load_butterfly()
_STARS = _make_stars()


STAR_PATHS = [
    ((63,  0), ( 0, 31)),   # corner to corner
    ((63,  4), ( 4, 31)),   # slightly inset end
    ((60,  0), ( 0, 27)),   # slightly inset start
]
STAR_DURATION = 0.9
STAR_INTERVAL = 1200.0  # 20 minutes
STAR_TRAIL    = 6
STAR_COLOR    = (120, 255, 120)   # light green


def _draw_shooting_star(img, progress, path):
    (sx, sy), (ex, ey) = path
    for i in range(STAR_TRAIL):
        t = progress - i * (STAR_DURATION / (STAR_TRAIL * 6))
        if t < 0:
            continue
        x = int(sx + t / STAR_DURATION * (ex - sx))
        y = int(sy + t / STAR_DURATION * (ey - sy))
        if 0 <= x < 64 and 0 <= y < 32:
            fade = 1 - i / STAR_TRAIL
            img.putpixel((x, y), tuple(int(c * fade) for c in STAR_COLOR))


def make_frame(angle, star_progress=None):
    img = Image.new("RGB", (64, 32), (0, 0, 0))
    d = ImageDraw.Draw(img)
    t = time.time()

    for x, y, phase, speed, color in _STARS:
        b = int(((math.sin(t * speed + phase) + 1) / 2) * 255)
        if color == 'blue':
            d.point((x, y), fill=(int(b * 0.027), int(b * 0.384), b))
        else:
            d.point((x, y), fill=(b, int(b * 0.35), 0))

    # Power curve: snaps fast through face-on, eases near edge-on
    phase = (angle % 360) / 360
    L = 1 - 4 * phase if phase < 0.5 else -3 + 4 * phase  # triangular -1..1
    scale_x = math.copysign(abs(L) ** 1.4, L)  # softer curve
    facing_front = scale_x >= 0

    sprite = _BUTTERFLY if facing_front else _BUTTERFLY.transpose(Image.FLIP_LEFT_RIGHT)

    new_w = max(1, round(abs(scale_x) * 37))
    scaled = sprite.resize((new_w, 27), Image.BILINEAR)

    if not facing_front:
        r, g, b, a = scaled.split()
        factor = int(255 * (0.45 + 0.55 * abs(scale_x)))
        r = r.point(lambda p: p * factor // 255)
        g = g.point(lambda p: p * factor // 255)
        b = b.point(lambda p: p * factor // 255)
        scaled = Image.merge("RGBA", (r, g, b, a))

    x_off = 32 - new_w // 2
    img.paste(scaled, (x_off, 3), scaled)

    if star_progress is not None:
        t, path = star_progress
        (sx, sy), (ex, ey) = path
        # Three stars: close at origin, spread apart at destination, slight time stagger
        offsets = [
            ((-1, -1), (-5, -5), +0.06),   # top streak, slight lead
            (( 0,  0), ( 0,  0),  0.0 ),   # center streak
            (( 1,  1), ( 4,  6), -0.06),   # bottom streak, slight lag
        ]
        for (dsx, dsy), (dex, dey), dt in offsets:
            _draw_shooting_star(img, t + dt, ((sx+dsx, sy+dsy), (ex+dex, ey+dey)))

    # Time in bottom-right corner (3x5 pixel font)
    now_str = time.strftime("%-I:%M")
    tw = len(now_str) * 4 - 1
    _draw_text(img, 63 - tw, 26, now_str, (160, 160, 160))

    return img


def main():
    opts = RGBMatrixOptions()
    opts.rows = 32
    opts.cols = 64
    opts.hardware_mapping = 'adafruit-hat'
    try:
        opts.brightness = int(open("/tmp/tidabit_brightness").read().strip())
    except:
        opts.brightness = 80
    opts.pwm_bits = 7

    matrix = RGBMatrix(options=opts)
    canvas = matrix.CreateFrameCanvas()

    angle = 0.0
    last_t = time.time()
    star_fired_at = -STAR_INTERVAL
    star_path = random.choice(STAR_PATHS)

    try:
        while True:
            now = time.time()
            angle = (angle + SPIN_SPEED * (now - last_t)) % 360
            last_t = now

            elapsed = now - star_fired_at
            if elapsed >= STAR_INTERVAL + STAR_DURATION:
                star_fired_at = now
                star_path = random.choice(STAR_PATHS)
            star_progress = (elapsed, star_path) if elapsed < STAR_DURATION else None

            canvas.SetImage(make_frame(angle, star_progress))
            canvas = matrix.SwapOnVSync(canvas)
            check_and_show_notification(matrix, canvas)
    except KeyboardInterrupt:
        matrix.Clear()


if __name__ == "__main__":
    main()
